### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by bourov** [yvesgit/fast.ai#2]
Says not authorized when try to sync via Github desktop

When try to upload directly via website:

Uploads are disabled.
File uploads require push access to this repository.

**Comment by yvesgit** [comment]
I invited you as a collaborator. I hope that will resolve privacy issues.

**Comment by bourov** [comment]
After accepting invitation, the upload through website works.  The Github app still has problems, but no longer critical , thank you, Yves !
